//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Input System/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""PlayerMovement"",
            ""id"": ""f24e43b6-dcf5-48c7-8242-493154a64bd8"",
            ""actions"": [
                {
                    ""name"": ""Forward"",
                    ""type"": ""Button"",
                    ""id"": ""698dd996-43b0-44a5-a792-4385cd8476b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Backward"",
                    ""type"": ""Button"",
                    ""id"": ""f9e0f72d-325a-4de9-8bb2-e104ab3a9ee5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""595f16cd-19a0-428e-8f64-f9293489938a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""9965efa7-33e9-4806-baae-d25af22b9e05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraRotateX"",
                    ""type"": ""Button"",
                    ""id"": ""47b5cd8a-12fd-4a5c-aaad-8edc8a231ce5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraRotateY"",
                    ""type"": ""Button"",
                    ""id"": ""dccc9889-fa7a-4910-9655-508bae486047"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityUp"",
                    ""type"": ""Button"",
                    ""id"": ""e637ea5d-6d4a-42c4-a0df-f508be8f5c16"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityDown"",
                    ""type"": ""Button"",
                    ""id"": ""537a764c-f061-43a7-9aec-a04b41f24c36"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityLeft"",
                    ""type"": ""Button"",
                    ""id"": ""1840b452-1782-4c60-83be-d66e75310c9c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityRight_DownPress"",
                    ""type"": ""Button"",
                    ""id"": ""7ac5af14-4ed0-4a7a-8817-50fc910ed6b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityRight_RelesePress"",
                    ""type"": ""Button"",
                    ""id"": ""b7721fd0-ab9a-47b4-97bf-383e0746611d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Respawn"",
                    ""type"": ""Button"",
                    ""id"": ""82cb90a0-e3d1-4a2a-910e-310560a18efa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quit"",
                    ""type"": ""Button"",
                    ""id"": ""52cd2f17-add6-46d6-ade0-173c0936ff98"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9b42e02b-79a8-4059-aa8b-14e4989c0ce0"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35bc038b-7e9d-4cc7-b673-e5b32bcadf6a"",
                    ""path"": ""<Keyboard>/#(W)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9e65701-2457-4069-9bd0-8dba3d3186ba"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""206091fd-570a-48ad-92e7-08c269161219"",
                    ""path"": ""<Keyboard>/#(S)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6681fe46-7afd-4f36-829f-f4884d1b5925"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2bc7386f-3260-4075-8f30-cb4a77bba447"",
                    ""path"": ""<Keyboard>/#(A)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07e39716-a5bc-4de8-acef-1464ba1cdfe9"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bee5263f-ed89-48f8-a10c-cf28202d6c46"",
                    ""path"": ""<Keyboard>/#(D)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b18687a8-12ad-46ac-9769-dbcd493af866"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotateX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""338510c4-a01d-465c-826f-8107f53b9f3a"",
                    ""path"": ""<Keyboard>/#(Q)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotateX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49426125-8fb7-4679-b03e-264d71fceb7c"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotateY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5cd08ed6-b6e3-4d1f-a1c6-135e85c08ac2"",
                    ""path"": ""<Keyboard>/#(E)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotateY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e98bb56-c7b1-4179-993f-d597601dbc12"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79ebe61b-f1ea-4a96-84c8-0c61d9745a51"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c994fb1-722d-4a7f-8430-4945a4fb4fb0"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab5172fc-069b-4759-b262-063d694fff6a"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fbd1f61-cfbf-4d0b-a616-5433eb99feb9"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""767b1b20-2aa3-475d-9855-5bfe495142bb"",
                    ""path"": ""<Keyboard>/#(C)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e2fc81d-e596-4f32-9f12-a1259dc7df5b"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityRight_DownPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""568413ee-2bb5-49c6-935d-d19b02cfeafc"",
                    ""path"": ""<Keyboard>/#(F)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityRight_DownPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79db51db-4abe-4a73-aef2-fc20a1a61b6e"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Respawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91de1d82-882b-4ae4-8e7e-901898bab023"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Respawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15ab2fff-f37e-4784-982f-10bc9ec0c789"",
                    ""path"": ""<Keyboard>/#(R)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Respawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b25617c-80cc-4a0d-9857-c4f0d581ae06"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ae1396e-9b6a-4275-91ad-e205a81ce4f6"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20a5db22-aba1-446f-b256-2070681b578c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c833d9d-8823-4888-a9fa-5d6aff465623"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityRight_RelesePress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3a20375-fa17-4b32-9cd0-ed2ab83b4da9"",
                    ""path"": ""<Keyboard>/#(F)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityRight_RelesePress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerMovement
        m_PlayerMovement = asset.FindActionMap("PlayerMovement", throwIfNotFound: true);
        m_PlayerMovement_Forward = m_PlayerMovement.FindAction("Forward", throwIfNotFound: true);
        m_PlayerMovement_Backward = m_PlayerMovement.FindAction("Backward", throwIfNotFound: true);
        m_PlayerMovement_Left = m_PlayerMovement.FindAction("Left", throwIfNotFound: true);
        m_PlayerMovement_Right = m_PlayerMovement.FindAction("Right", throwIfNotFound: true);
        m_PlayerMovement_CameraRotateX = m_PlayerMovement.FindAction("CameraRotateX", throwIfNotFound: true);
        m_PlayerMovement_CameraRotateY = m_PlayerMovement.FindAction("CameraRotateY", throwIfNotFound: true);
        m_PlayerMovement_AbilityUp = m_PlayerMovement.FindAction("AbilityUp", throwIfNotFound: true);
        m_PlayerMovement_AbilityDown = m_PlayerMovement.FindAction("AbilityDown", throwIfNotFound: true);
        m_PlayerMovement_AbilityLeft = m_PlayerMovement.FindAction("AbilityLeft", throwIfNotFound: true);
        m_PlayerMovement_AbilityRight_DownPress = m_PlayerMovement.FindAction("AbilityRight_DownPress", throwIfNotFound: true);
        m_PlayerMovement_AbilityRight_RelesePress = m_PlayerMovement.FindAction("AbilityRight_RelesePress", throwIfNotFound: true);
        m_PlayerMovement_Respawn = m_PlayerMovement.FindAction("Respawn", throwIfNotFound: true);
        m_PlayerMovement_Quit = m_PlayerMovement.FindAction("Quit", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMovement
    private readonly InputActionMap m_PlayerMovement;
    private List<IPlayerMovementActions> m_PlayerMovementActionsCallbackInterfaces = new List<IPlayerMovementActions>();
    private readonly InputAction m_PlayerMovement_Forward;
    private readonly InputAction m_PlayerMovement_Backward;
    private readonly InputAction m_PlayerMovement_Left;
    private readonly InputAction m_PlayerMovement_Right;
    private readonly InputAction m_PlayerMovement_CameraRotateX;
    private readonly InputAction m_PlayerMovement_CameraRotateY;
    private readonly InputAction m_PlayerMovement_AbilityUp;
    private readonly InputAction m_PlayerMovement_AbilityDown;
    private readonly InputAction m_PlayerMovement_AbilityLeft;
    private readonly InputAction m_PlayerMovement_AbilityRight_DownPress;
    private readonly InputAction m_PlayerMovement_AbilityRight_RelesePress;
    private readonly InputAction m_PlayerMovement_Respawn;
    private readonly InputAction m_PlayerMovement_Quit;
    public struct PlayerMovementActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerMovementActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Forward => m_Wrapper.m_PlayerMovement_Forward;
        public InputAction @Backward => m_Wrapper.m_PlayerMovement_Backward;
        public InputAction @Left => m_Wrapper.m_PlayerMovement_Left;
        public InputAction @Right => m_Wrapper.m_PlayerMovement_Right;
        public InputAction @CameraRotateX => m_Wrapper.m_PlayerMovement_CameraRotateX;
        public InputAction @CameraRotateY => m_Wrapper.m_PlayerMovement_CameraRotateY;
        public InputAction @AbilityUp => m_Wrapper.m_PlayerMovement_AbilityUp;
        public InputAction @AbilityDown => m_Wrapper.m_PlayerMovement_AbilityDown;
        public InputAction @AbilityLeft => m_Wrapper.m_PlayerMovement_AbilityLeft;
        public InputAction @AbilityRight_DownPress => m_Wrapper.m_PlayerMovement_AbilityRight_DownPress;
        public InputAction @AbilityRight_RelesePress => m_Wrapper.m_PlayerMovement_AbilityRight_RelesePress;
        public InputAction @Respawn => m_Wrapper.m_PlayerMovement_Respawn;
        public InputAction @Quit => m_Wrapper.m_PlayerMovement_Quit;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMovementActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerMovementActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Add(instance);
            @Forward.started += instance.OnForward;
            @Forward.performed += instance.OnForward;
            @Forward.canceled += instance.OnForward;
            @Backward.started += instance.OnBackward;
            @Backward.performed += instance.OnBackward;
            @Backward.canceled += instance.OnBackward;
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
            @CameraRotateX.started += instance.OnCameraRotateX;
            @CameraRotateX.performed += instance.OnCameraRotateX;
            @CameraRotateX.canceled += instance.OnCameraRotateX;
            @CameraRotateY.started += instance.OnCameraRotateY;
            @CameraRotateY.performed += instance.OnCameraRotateY;
            @CameraRotateY.canceled += instance.OnCameraRotateY;
            @AbilityUp.started += instance.OnAbilityUp;
            @AbilityUp.performed += instance.OnAbilityUp;
            @AbilityUp.canceled += instance.OnAbilityUp;
            @AbilityDown.started += instance.OnAbilityDown;
            @AbilityDown.performed += instance.OnAbilityDown;
            @AbilityDown.canceled += instance.OnAbilityDown;
            @AbilityLeft.started += instance.OnAbilityLeft;
            @AbilityLeft.performed += instance.OnAbilityLeft;
            @AbilityLeft.canceled += instance.OnAbilityLeft;
            @AbilityRight_DownPress.started += instance.OnAbilityRight_DownPress;
            @AbilityRight_DownPress.performed += instance.OnAbilityRight_DownPress;
            @AbilityRight_DownPress.canceled += instance.OnAbilityRight_DownPress;
            @AbilityRight_RelesePress.started += instance.OnAbilityRight_RelesePress;
            @AbilityRight_RelesePress.performed += instance.OnAbilityRight_RelesePress;
            @AbilityRight_RelesePress.canceled += instance.OnAbilityRight_RelesePress;
            @Respawn.started += instance.OnRespawn;
            @Respawn.performed += instance.OnRespawn;
            @Respawn.canceled += instance.OnRespawn;
            @Quit.started += instance.OnQuit;
            @Quit.performed += instance.OnQuit;
            @Quit.canceled += instance.OnQuit;
        }

        private void UnregisterCallbacks(IPlayerMovementActions instance)
        {
            @Forward.started -= instance.OnForward;
            @Forward.performed -= instance.OnForward;
            @Forward.canceled -= instance.OnForward;
            @Backward.started -= instance.OnBackward;
            @Backward.performed -= instance.OnBackward;
            @Backward.canceled -= instance.OnBackward;
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
            @CameraRotateX.started -= instance.OnCameraRotateX;
            @CameraRotateX.performed -= instance.OnCameraRotateX;
            @CameraRotateX.canceled -= instance.OnCameraRotateX;
            @CameraRotateY.started -= instance.OnCameraRotateY;
            @CameraRotateY.performed -= instance.OnCameraRotateY;
            @CameraRotateY.canceled -= instance.OnCameraRotateY;
            @AbilityUp.started -= instance.OnAbilityUp;
            @AbilityUp.performed -= instance.OnAbilityUp;
            @AbilityUp.canceled -= instance.OnAbilityUp;
            @AbilityDown.started -= instance.OnAbilityDown;
            @AbilityDown.performed -= instance.OnAbilityDown;
            @AbilityDown.canceled -= instance.OnAbilityDown;
            @AbilityLeft.started -= instance.OnAbilityLeft;
            @AbilityLeft.performed -= instance.OnAbilityLeft;
            @AbilityLeft.canceled -= instance.OnAbilityLeft;
            @AbilityRight_DownPress.started -= instance.OnAbilityRight_DownPress;
            @AbilityRight_DownPress.performed -= instance.OnAbilityRight_DownPress;
            @AbilityRight_DownPress.canceled -= instance.OnAbilityRight_DownPress;
            @AbilityRight_RelesePress.started -= instance.OnAbilityRight_RelesePress;
            @AbilityRight_RelesePress.performed -= instance.OnAbilityRight_RelesePress;
            @AbilityRight_RelesePress.canceled -= instance.OnAbilityRight_RelesePress;
            @Respawn.started -= instance.OnRespawn;
            @Respawn.performed -= instance.OnRespawn;
            @Respawn.canceled -= instance.OnRespawn;
            @Quit.started -= instance.OnQuit;
            @Quit.performed -= instance.OnQuit;
            @Quit.canceled -= instance.OnQuit;
        }

        public void RemoveCallbacks(IPlayerMovementActions instance)
        {
            if (m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerMovementActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerMovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerMovementActions @PlayerMovement => new PlayerMovementActions(this);
    public interface IPlayerMovementActions
    {
        void OnForward(InputAction.CallbackContext context);
        void OnBackward(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
        void OnCameraRotateX(InputAction.CallbackContext context);
        void OnCameraRotateY(InputAction.CallbackContext context);
        void OnAbilityUp(InputAction.CallbackContext context);
        void OnAbilityDown(InputAction.CallbackContext context);
        void OnAbilityLeft(InputAction.CallbackContext context);
        void OnAbilityRight_DownPress(InputAction.CallbackContext context);
        void OnAbilityRight_RelesePress(InputAction.CallbackContext context);
        void OnRespawn(InputAction.CallbackContext context);
        void OnQuit(InputAction.CallbackContext context);
    }
}
