//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Input System/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""PlayerMovement"",
            ""id"": ""f24e43b6-dcf5-48c7-8242-493154a64bd8"",
            ""actions"": [
                {
                    ""name"": ""Forward_Down"",
                    ""type"": ""Button"",
                    ""id"": ""698dd996-43b0-44a5-a792-4385cd8476b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Forward_Up"",
                    ""type"": ""Button"",
                    ""id"": ""8282b741-e069-41c2-95d9-cd28074c081c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Backward_Down"",
                    ""type"": ""Button"",
                    ""id"": ""f9e0f72d-325a-4de9-8bb2-e104ab3a9ee5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Backward_Up"",
                    ""type"": ""Button"",
                    ""id"": ""2fbc98d3-8bf9-4cf0-829c-e22502d206ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left_Down"",
                    ""type"": ""Button"",
                    ""id"": ""595f16cd-19a0-428e-8f64-f9293489938a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left_Up"",
                    ""type"": ""Button"",
                    ""id"": ""9c31b299-341e-4736-a10b-b79f515a3ac1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right_Down"",
                    ""type"": ""Button"",
                    ""id"": ""9965efa7-33e9-4806-baae-d25af22b9e05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right_Up"",
                    ""type"": ""Button"",
                    ""id"": ""75955030-b0f8-4d33-8a9a-a4d8767bd1b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraRotateX"",
                    ""type"": ""Button"",
                    ""id"": ""47b5cd8a-12fd-4a5c-aaad-8edc8a231ce5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraRotateY"",
                    ""type"": ""Button"",
                    ""id"": ""dccc9889-fa7a-4910-9655-508bae486047"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityUp_Down"",
                    ""type"": ""Button"",
                    ""id"": ""e637ea5d-6d4a-42c4-a0df-f508be8f5c16"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityUp_Up"",
                    ""type"": ""Button"",
                    ""id"": ""4d7e45b4-d548-4a30-a1cc-6cff58127fdd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityDown_Down"",
                    ""type"": ""Button"",
                    ""id"": ""537a764c-f061-43a7-9aec-a04b41f24c36"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityDown_Up"",
                    ""type"": ""Button"",
                    ""id"": ""c6e95a46-ec3e-42f8-b590-3b0800d306e3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityLeft"",
                    ""type"": ""Button"",
                    ""id"": ""1840b452-1782-4c60-83be-d66e75310c9c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityRight_DownPress"",
                    ""type"": ""Button"",
                    ""id"": ""7ac5af14-4ed0-4a7a-8817-50fc910ed6b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityRight_RelesePress"",
                    ""type"": ""Button"",
                    ""id"": ""b7721fd0-ab9a-47b4-97bf-383e0746611d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Respawn"",
                    ""type"": ""Button"",
                    ""id"": ""82cb90a0-e3d1-4a2a-910e-310560a18efa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quit"",
                    ""type"": ""Button"",
                    ""id"": ""52cd2f17-add6-46d6-ade0-173c0936ff98"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu_Back"",
                    ""type"": ""Button"",
                    ""id"": ""dcb7f92d-9aee-4ee7-82a8-ac0247e8ec10"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DialogueSkip_Pressed"",
                    ""type"": ""Button"",
                    ""id"": ""4a239305-b40f-467c-a1c5-27c204531502"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DialogueNext_Pressed"",
                    ""type"": ""Button"",
                    ""id"": ""785c42ca-c17f-47fc-bc49-33829ffb13e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractButton_Pressed"",
                    ""type"": ""Button"",
                    ""id"": ""c24cdf9d-b06c-4067-903a-478c21b95358"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuNavigation_Up"",
                    ""type"": ""Button"",
                    ""id"": ""6c3584a7-963d-4270-94d5-d72c20038d11"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuNavigation_Down"",
                    ""type"": ""Button"",
                    ""id"": ""3d9abcb6-de64-4bc2-8ee9-9c834a82f6b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuNavigation_Left"",
                    ""type"": ""Button"",
                    ""id"": ""afc9eab6-dffb-405a-a16a-c5fdc7589999"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuNavigation_Right"",
                    ""type"": ""Button"",
                    ""id"": ""36cb94a5-8d1a-4135-bdbd-5475da7f3798"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OptionsMenuShift_Left"",
                    ""type"": ""Button"",
                    ""id"": ""cc1bc000-a721-40cc-9de4-e8f38d9ae13f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OptionsMenuShift_Right"",
                    ""type"": ""Button"",
                    ""id"": ""cfa6db3d-1ce9-4cd4-9351-7d938cb1f0de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9b42e02b-79a8-4059-aa8b-14e4989c0ce0"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Forward_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35bc038b-7e9d-4cc7-b673-e5b32bcadf6a"",
                    ""path"": ""<Keyboard>/#(W)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Forward_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9e65701-2457-4069-9bd0-8dba3d3186ba"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Backward_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""206091fd-570a-48ad-92e7-08c269161219"",
                    ""path"": ""<Keyboard>/#(S)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Backward_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6681fe46-7afd-4f36-829f-f4884d1b5925"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2bc7386f-3260-4075-8f30-cb4a77bba447"",
                    ""path"": ""<Keyboard>/#(A)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07e39716-a5bc-4de8-acef-1464ba1cdfe9"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bee5263f-ed89-48f8-a10c-cf28202d6c46"",
                    ""path"": ""<Keyboard>/#(D)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b18687a8-12ad-46ac-9769-dbcd493af866"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotateX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""338510c4-a01d-465c-826f-8107f53b9f3a"",
                    ""path"": ""<Keyboard>/#(Q)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotateX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49426125-8fb7-4679-b03e-264d71fceb7c"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotateY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5cd08ed6-b6e3-4d1f-a1c6-135e85c08ac2"",
                    ""path"": ""<Keyboard>/#(E)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotateY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e98bb56-c7b1-4179-993f-d597601dbc12"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityUp_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79ebe61b-f1ea-4a96-84c8-0c61d9745a51"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityUp_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c994fb1-722d-4a7f-8430-4945a4fb4fb0"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityDown_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab5172fc-069b-4759-b262-063d694fff6a"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityDown_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fbd1f61-cfbf-4d0b-a616-5433eb99feb9"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""767b1b20-2aa3-475d-9855-5bfe495142bb"",
                    ""path"": ""<Keyboard>/#(C)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e2fc81d-e596-4f32-9f12-a1259dc7df5b"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityRight_DownPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""568413ee-2bb5-49c6-935d-d19b02cfeafc"",
                    ""path"": ""<Keyboard>/#(F)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityRight_DownPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79db51db-4abe-4a73-aef2-fc20a1a61b6e"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Respawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91de1d82-882b-4ae4-8e7e-901898bab023"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Respawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15ab2fff-f37e-4784-982f-10bc9ec0c789"",
                    ""path"": ""<Keyboard>/#(R)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Respawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b25617c-80cc-4a0d-9857-c4f0d581ae06"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ae1396e-9b6a-4275-91ad-e205a81ce4f6"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20a5db22-aba1-446f-b256-2070681b578c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c833d9d-8823-4888-a9fa-5d6aff465623"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityRight_RelesePress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3a20375-fa17-4b32-9cd0-ed2ab83b4da9"",
                    ""path"": ""<Keyboard>/#(F)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityRight_RelesePress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26d785ca-036f-4ee7-9ea0-7d5e739a7db4"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Forward_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b4b0ac2-0a4e-40c8-89bc-681e9b61d7b9"",
                    ""path"": ""<Keyboard>/#(W)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Forward_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""125c5e19-44a5-417f-9701-e961b089c256"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Backward_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75fa4698-c6aa-428c-9ce4-c0ea129b4a12"",
                    ""path"": ""<Keyboard>/#(S)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Backward_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2339d31d-b3e7-4bea-a0c2-3d6d0c30ac04"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""afbb416f-9d92-49ab-832e-1e07dc8437d8"",
                    ""path"": ""<Keyboard>/#(A)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96a7635a-29d9-457e-924e-7db0d8d9c647"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62b543bb-12a2-4883-90ed-137349dc8310"",
                    ""path"": ""<Keyboard>/#(D)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52c85c67-284f-4c8d-a6b8-b0fc10a81ac0"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu_Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9bd9afcf-c6fb-408b-9da3-aca0996ff617"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu_Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a480ae5-2dec-4244-b3e9-015747f468c8"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu_Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""249a91fa-4cb0-439a-b000-b557a0bd54fa"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityUp_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6419b243-4d8e-4c7e-ad37-fa9955afdf13"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityUp_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1f098fd-1b29-43e5-a5dc-181c7418b2bb"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityDown_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42e18646-9010-4d5d-b940-9b24fc4ce0c6"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityDown_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""237bd8df-ab81-4ecb-90f8-fbde7edf1135"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueSkip_Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40e52bb9-7cff-4570-b0c7-4f83309533d0"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueSkip_Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85b5c81c-753c-4d60-91f1-22e6ee80af71"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueSkip_Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9afe7651-2029-4e69-8501-302c62177cda"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueNext_Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92d67012-b7c4-4f1f-aeb2-ad49723c8f0f"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueNext_Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""974ab7f0-4a91-428f-8c96-6ca69354aee5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueNext_Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4ae27a7-6247-4fda-9004-bb1d58b9d7e9"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractButton_Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11ad2deb-5a7d-4e6e-82d6-d82117205fcf"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractButton_Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2e03dc3-4418-4c83-98de-c1acd04d2d9b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractButton_Pressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d238093-1c25-455d-aa35-9607665ce74c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuNavigation_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d436823-9120-45d3-8f06-693602c2297f"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuNavigation_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3dc715f7-e3ed-4f75-a71f-499e9fc44379"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuNavigation_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84ed2ba0-a570-4ba4-81fb-39efafa3aed1"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuNavigation_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78cef5ca-2837-4c27-9c96-25955dc34acf"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuNavigation_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b55febc-c5de-4012-961f-523e0c37eb3b"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuNavigation_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""614e56d9-c9e3-41e8-b12d-312b2cdb805c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuNavigation_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35edd3d8-a8d9-44aa-bd48-a1b080ee47f2"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuNavigation_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fae90a00-0072-47a6-b5b8-bff4130c7cf2"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OptionsMenuShift_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9fb62b2-cb7a-4bd4-a25d-e7c045863a57"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OptionsMenuShift_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerMovement
        m_PlayerMovement = asset.FindActionMap("PlayerMovement", throwIfNotFound: true);
        m_PlayerMovement_Forward_Down = m_PlayerMovement.FindAction("Forward_Down", throwIfNotFound: true);
        m_PlayerMovement_Forward_Up = m_PlayerMovement.FindAction("Forward_Up", throwIfNotFound: true);
        m_PlayerMovement_Backward_Down = m_PlayerMovement.FindAction("Backward_Down", throwIfNotFound: true);
        m_PlayerMovement_Backward_Up = m_PlayerMovement.FindAction("Backward_Up", throwIfNotFound: true);
        m_PlayerMovement_Left_Down = m_PlayerMovement.FindAction("Left_Down", throwIfNotFound: true);
        m_PlayerMovement_Left_Up = m_PlayerMovement.FindAction("Left_Up", throwIfNotFound: true);
        m_PlayerMovement_Right_Down = m_PlayerMovement.FindAction("Right_Down", throwIfNotFound: true);
        m_PlayerMovement_Right_Up = m_PlayerMovement.FindAction("Right_Up", throwIfNotFound: true);
        m_PlayerMovement_CameraRotateX = m_PlayerMovement.FindAction("CameraRotateX", throwIfNotFound: true);
        m_PlayerMovement_CameraRotateY = m_PlayerMovement.FindAction("CameraRotateY", throwIfNotFound: true);
        m_PlayerMovement_AbilityUp_Down = m_PlayerMovement.FindAction("AbilityUp_Down", throwIfNotFound: true);
        m_PlayerMovement_AbilityUp_Up = m_PlayerMovement.FindAction("AbilityUp_Up", throwIfNotFound: true);
        m_PlayerMovement_AbilityDown_Down = m_PlayerMovement.FindAction("AbilityDown_Down", throwIfNotFound: true);
        m_PlayerMovement_AbilityDown_Up = m_PlayerMovement.FindAction("AbilityDown_Up", throwIfNotFound: true);
        m_PlayerMovement_AbilityLeft = m_PlayerMovement.FindAction("AbilityLeft", throwIfNotFound: true);
        m_PlayerMovement_AbilityRight_DownPress = m_PlayerMovement.FindAction("AbilityRight_DownPress", throwIfNotFound: true);
        m_PlayerMovement_AbilityRight_RelesePress = m_PlayerMovement.FindAction("AbilityRight_RelesePress", throwIfNotFound: true);
        m_PlayerMovement_Respawn = m_PlayerMovement.FindAction("Respawn", throwIfNotFound: true);
        m_PlayerMovement_Quit = m_PlayerMovement.FindAction("Quit", throwIfNotFound: true);
        m_PlayerMovement_Menu_Back = m_PlayerMovement.FindAction("Menu_Back", throwIfNotFound: true);
        m_PlayerMovement_DialogueSkip_Pressed = m_PlayerMovement.FindAction("DialogueSkip_Pressed", throwIfNotFound: true);
        m_PlayerMovement_DialogueNext_Pressed = m_PlayerMovement.FindAction("DialogueNext_Pressed", throwIfNotFound: true);
        m_PlayerMovement_InteractButton_Pressed = m_PlayerMovement.FindAction("InteractButton_Pressed", throwIfNotFound: true);
        m_PlayerMovement_MenuNavigation_Up = m_PlayerMovement.FindAction("MenuNavigation_Up", throwIfNotFound: true);
        m_PlayerMovement_MenuNavigation_Down = m_PlayerMovement.FindAction("MenuNavigation_Down", throwIfNotFound: true);
        m_PlayerMovement_MenuNavigation_Left = m_PlayerMovement.FindAction("MenuNavigation_Left", throwIfNotFound: true);
        m_PlayerMovement_MenuNavigation_Right = m_PlayerMovement.FindAction("MenuNavigation_Right", throwIfNotFound: true);
        m_PlayerMovement_OptionsMenuShift_Left = m_PlayerMovement.FindAction("OptionsMenuShift_Left", throwIfNotFound: true);
        m_PlayerMovement_OptionsMenuShift_Right = m_PlayerMovement.FindAction("OptionsMenuShift_Right", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMovement
    private readonly InputActionMap m_PlayerMovement;
    private List<IPlayerMovementActions> m_PlayerMovementActionsCallbackInterfaces = new List<IPlayerMovementActions>();
    private readonly InputAction m_PlayerMovement_Forward_Down;
    private readonly InputAction m_PlayerMovement_Forward_Up;
    private readonly InputAction m_PlayerMovement_Backward_Down;
    private readonly InputAction m_PlayerMovement_Backward_Up;
    private readonly InputAction m_PlayerMovement_Left_Down;
    private readonly InputAction m_PlayerMovement_Left_Up;
    private readonly InputAction m_PlayerMovement_Right_Down;
    private readonly InputAction m_PlayerMovement_Right_Up;
    private readonly InputAction m_PlayerMovement_CameraRotateX;
    private readonly InputAction m_PlayerMovement_CameraRotateY;
    private readonly InputAction m_PlayerMovement_AbilityUp_Down;
    private readonly InputAction m_PlayerMovement_AbilityUp_Up;
    private readonly InputAction m_PlayerMovement_AbilityDown_Down;
    private readonly InputAction m_PlayerMovement_AbilityDown_Up;
    private readonly InputAction m_PlayerMovement_AbilityLeft;
    private readonly InputAction m_PlayerMovement_AbilityRight_DownPress;
    private readonly InputAction m_PlayerMovement_AbilityRight_RelesePress;
    private readonly InputAction m_PlayerMovement_Respawn;
    private readonly InputAction m_PlayerMovement_Quit;
    private readonly InputAction m_PlayerMovement_Menu_Back;
    private readonly InputAction m_PlayerMovement_DialogueSkip_Pressed;
    private readonly InputAction m_PlayerMovement_DialogueNext_Pressed;
    private readonly InputAction m_PlayerMovement_InteractButton_Pressed;
    private readonly InputAction m_PlayerMovement_MenuNavigation_Up;
    private readonly InputAction m_PlayerMovement_MenuNavigation_Down;
    private readonly InputAction m_PlayerMovement_MenuNavigation_Left;
    private readonly InputAction m_PlayerMovement_MenuNavigation_Right;
    private readonly InputAction m_PlayerMovement_OptionsMenuShift_Left;
    private readonly InputAction m_PlayerMovement_OptionsMenuShift_Right;
    public struct PlayerMovementActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerMovementActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Forward_Down => m_Wrapper.m_PlayerMovement_Forward_Down;
        public InputAction @Forward_Up => m_Wrapper.m_PlayerMovement_Forward_Up;
        public InputAction @Backward_Down => m_Wrapper.m_PlayerMovement_Backward_Down;
        public InputAction @Backward_Up => m_Wrapper.m_PlayerMovement_Backward_Up;
        public InputAction @Left_Down => m_Wrapper.m_PlayerMovement_Left_Down;
        public InputAction @Left_Up => m_Wrapper.m_PlayerMovement_Left_Up;
        public InputAction @Right_Down => m_Wrapper.m_PlayerMovement_Right_Down;
        public InputAction @Right_Up => m_Wrapper.m_PlayerMovement_Right_Up;
        public InputAction @CameraRotateX => m_Wrapper.m_PlayerMovement_CameraRotateX;
        public InputAction @CameraRotateY => m_Wrapper.m_PlayerMovement_CameraRotateY;
        public InputAction @AbilityUp_Down => m_Wrapper.m_PlayerMovement_AbilityUp_Down;
        public InputAction @AbilityUp_Up => m_Wrapper.m_PlayerMovement_AbilityUp_Up;
        public InputAction @AbilityDown_Down => m_Wrapper.m_PlayerMovement_AbilityDown_Down;
        public InputAction @AbilityDown_Up => m_Wrapper.m_PlayerMovement_AbilityDown_Up;
        public InputAction @AbilityLeft => m_Wrapper.m_PlayerMovement_AbilityLeft;
        public InputAction @AbilityRight_DownPress => m_Wrapper.m_PlayerMovement_AbilityRight_DownPress;
        public InputAction @AbilityRight_RelesePress => m_Wrapper.m_PlayerMovement_AbilityRight_RelesePress;
        public InputAction @Respawn => m_Wrapper.m_PlayerMovement_Respawn;
        public InputAction @Quit => m_Wrapper.m_PlayerMovement_Quit;
        public InputAction @Menu_Back => m_Wrapper.m_PlayerMovement_Menu_Back;
        public InputAction @DialogueSkip_Pressed => m_Wrapper.m_PlayerMovement_DialogueSkip_Pressed;
        public InputAction @DialogueNext_Pressed => m_Wrapper.m_PlayerMovement_DialogueNext_Pressed;
        public InputAction @InteractButton_Pressed => m_Wrapper.m_PlayerMovement_InteractButton_Pressed;
        public InputAction @MenuNavigation_Up => m_Wrapper.m_PlayerMovement_MenuNavigation_Up;
        public InputAction @MenuNavigation_Down => m_Wrapper.m_PlayerMovement_MenuNavigation_Down;
        public InputAction @MenuNavigation_Left => m_Wrapper.m_PlayerMovement_MenuNavigation_Left;
        public InputAction @MenuNavigation_Right => m_Wrapper.m_PlayerMovement_MenuNavigation_Right;
        public InputAction @OptionsMenuShift_Left => m_Wrapper.m_PlayerMovement_OptionsMenuShift_Left;
        public InputAction @OptionsMenuShift_Right => m_Wrapper.m_PlayerMovement_OptionsMenuShift_Right;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMovementActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerMovementActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Add(instance);
            @Forward_Down.started += instance.OnForward_Down;
            @Forward_Down.performed += instance.OnForward_Down;
            @Forward_Down.canceled += instance.OnForward_Down;
            @Forward_Up.started += instance.OnForward_Up;
            @Forward_Up.performed += instance.OnForward_Up;
            @Forward_Up.canceled += instance.OnForward_Up;
            @Backward_Down.started += instance.OnBackward_Down;
            @Backward_Down.performed += instance.OnBackward_Down;
            @Backward_Down.canceled += instance.OnBackward_Down;
            @Backward_Up.started += instance.OnBackward_Up;
            @Backward_Up.performed += instance.OnBackward_Up;
            @Backward_Up.canceled += instance.OnBackward_Up;
            @Left_Down.started += instance.OnLeft_Down;
            @Left_Down.performed += instance.OnLeft_Down;
            @Left_Down.canceled += instance.OnLeft_Down;
            @Left_Up.started += instance.OnLeft_Up;
            @Left_Up.performed += instance.OnLeft_Up;
            @Left_Up.canceled += instance.OnLeft_Up;
            @Right_Down.started += instance.OnRight_Down;
            @Right_Down.performed += instance.OnRight_Down;
            @Right_Down.canceled += instance.OnRight_Down;
            @Right_Up.started += instance.OnRight_Up;
            @Right_Up.performed += instance.OnRight_Up;
            @Right_Up.canceled += instance.OnRight_Up;
            @CameraRotateX.started += instance.OnCameraRotateX;
            @CameraRotateX.performed += instance.OnCameraRotateX;
            @CameraRotateX.canceled += instance.OnCameraRotateX;
            @CameraRotateY.started += instance.OnCameraRotateY;
            @CameraRotateY.performed += instance.OnCameraRotateY;
            @CameraRotateY.canceled += instance.OnCameraRotateY;
            @AbilityUp_Down.started += instance.OnAbilityUp_Down;
            @AbilityUp_Down.performed += instance.OnAbilityUp_Down;
            @AbilityUp_Down.canceled += instance.OnAbilityUp_Down;
            @AbilityUp_Up.started += instance.OnAbilityUp_Up;
            @AbilityUp_Up.performed += instance.OnAbilityUp_Up;
            @AbilityUp_Up.canceled += instance.OnAbilityUp_Up;
            @AbilityDown_Down.started += instance.OnAbilityDown_Down;
            @AbilityDown_Down.performed += instance.OnAbilityDown_Down;
            @AbilityDown_Down.canceled += instance.OnAbilityDown_Down;
            @AbilityDown_Up.started += instance.OnAbilityDown_Up;
            @AbilityDown_Up.performed += instance.OnAbilityDown_Up;
            @AbilityDown_Up.canceled += instance.OnAbilityDown_Up;
            @AbilityLeft.started += instance.OnAbilityLeft;
            @AbilityLeft.performed += instance.OnAbilityLeft;
            @AbilityLeft.canceled += instance.OnAbilityLeft;
            @AbilityRight_DownPress.started += instance.OnAbilityRight_DownPress;
            @AbilityRight_DownPress.performed += instance.OnAbilityRight_DownPress;
            @AbilityRight_DownPress.canceled += instance.OnAbilityRight_DownPress;
            @AbilityRight_RelesePress.started += instance.OnAbilityRight_RelesePress;
            @AbilityRight_RelesePress.performed += instance.OnAbilityRight_RelesePress;
            @AbilityRight_RelesePress.canceled += instance.OnAbilityRight_RelesePress;
            @Respawn.started += instance.OnRespawn;
            @Respawn.performed += instance.OnRespawn;
            @Respawn.canceled += instance.OnRespawn;
            @Quit.started += instance.OnQuit;
            @Quit.performed += instance.OnQuit;
            @Quit.canceled += instance.OnQuit;
            @Menu_Back.started += instance.OnMenu_Back;
            @Menu_Back.performed += instance.OnMenu_Back;
            @Menu_Back.canceled += instance.OnMenu_Back;
            @DialogueSkip_Pressed.started += instance.OnDialogueSkip_Pressed;
            @DialogueSkip_Pressed.performed += instance.OnDialogueSkip_Pressed;
            @DialogueSkip_Pressed.canceled += instance.OnDialogueSkip_Pressed;
            @DialogueNext_Pressed.started += instance.OnDialogueNext_Pressed;
            @DialogueNext_Pressed.performed += instance.OnDialogueNext_Pressed;
            @DialogueNext_Pressed.canceled += instance.OnDialogueNext_Pressed;
            @InteractButton_Pressed.started += instance.OnInteractButton_Pressed;
            @InteractButton_Pressed.performed += instance.OnInteractButton_Pressed;
            @InteractButton_Pressed.canceled += instance.OnInteractButton_Pressed;
            @MenuNavigation_Up.started += instance.OnMenuNavigation_Up;
            @MenuNavigation_Up.performed += instance.OnMenuNavigation_Up;
            @MenuNavigation_Up.canceled += instance.OnMenuNavigation_Up;
            @MenuNavigation_Down.started += instance.OnMenuNavigation_Down;
            @MenuNavigation_Down.performed += instance.OnMenuNavigation_Down;
            @MenuNavigation_Down.canceled += instance.OnMenuNavigation_Down;
            @MenuNavigation_Left.started += instance.OnMenuNavigation_Left;
            @MenuNavigation_Left.performed += instance.OnMenuNavigation_Left;
            @MenuNavigation_Left.canceled += instance.OnMenuNavigation_Left;
            @MenuNavigation_Right.started += instance.OnMenuNavigation_Right;
            @MenuNavigation_Right.performed += instance.OnMenuNavigation_Right;
            @MenuNavigation_Right.canceled += instance.OnMenuNavigation_Right;
            @OptionsMenuShift_Left.started += instance.OnOptionsMenuShift_Left;
            @OptionsMenuShift_Left.performed += instance.OnOptionsMenuShift_Left;
            @OptionsMenuShift_Left.canceled += instance.OnOptionsMenuShift_Left;
            @OptionsMenuShift_Right.started += instance.OnOptionsMenuShift_Right;
            @OptionsMenuShift_Right.performed += instance.OnOptionsMenuShift_Right;
            @OptionsMenuShift_Right.canceled += instance.OnOptionsMenuShift_Right;
        }

        private void UnregisterCallbacks(IPlayerMovementActions instance)
        {
            @Forward_Down.started -= instance.OnForward_Down;
            @Forward_Down.performed -= instance.OnForward_Down;
            @Forward_Down.canceled -= instance.OnForward_Down;
            @Forward_Up.started -= instance.OnForward_Up;
            @Forward_Up.performed -= instance.OnForward_Up;
            @Forward_Up.canceled -= instance.OnForward_Up;
            @Backward_Down.started -= instance.OnBackward_Down;
            @Backward_Down.performed -= instance.OnBackward_Down;
            @Backward_Down.canceled -= instance.OnBackward_Down;
            @Backward_Up.started -= instance.OnBackward_Up;
            @Backward_Up.performed -= instance.OnBackward_Up;
            @Backward_Up.canceled -= instance.OnBackward_Up;
            @Left_Down.started -= instance.OnLeft_Down;
            @Left_Down.performed -= instance.OnLeft_Down;
            @Left_Down.canceled -= instance.OnLeft_Down;
            @Left_Up.started -= instance.OnLeft_Up;
            @Left_Up.performed -= instance.OnLeft_Up;
            @Left_Up.canceled -= instance.OnLeft_Up;
            @Right_Down.started -= instance.OnRight_Down;
            @Right_Down.performed -= instance.OnRight_Down;
            @Right_Down.canceled -= instance.OnRight_Down;
            @Right_Up.started -= instance.OnRight_Up;
            @Right_Up.performed -= instance.OnRight_Up;
            @Right_Up.canceled -= instance.OnRight_Up;
            @CameraRotateX.started -= instance.OnCameraRotateX;
            @CameraRotateX.performed -= instance.OnCameraRotateX;
            @CameraRotateX.canceled -= instance.OnCameraRotateX;
            @CameraRotateY.started -= instance.OnCameraRotateY;
            @CameraRotateY.performed -= instance.OnCameraRotateY;
            @CameraRotateY.canceled -= instance.OnCameraRotateY;
            @AbilityUp_Down.started -= instance.OnAbilityUp_Down;
            @AbilityUp_Down.performed -= instance.OnAbilityUp_Down;
            @AbilityUp_Down.canceled -= instance.OnAbilityUp_Down;
            @AbilityUp_Up.started -= instance.OnAbilityUp_Up;
            @AbilityUp_Up.performed -= instance.OnAbilityUp_Up;
            @AbilityUp_Up.canceled -= instance.OnAbilityUp_Up;
            @AbilityDown_Down.started -= instance.OnAbilityDown_Down;
            @AbilityDown_Down.performed -= instance.OnAbilityDown_Down;
            @AbilityDown_Down.canceled -= instance.OnAbilityDown_Down;
            @AbilityDown_Up.started -= instance.OnAbilityDown_Up;
            @AbilityDown_Up.performed -= instance.OnAbilityDown_Up;
            @AbilityDown_Up.canceled -= instance.OnAbilityDown_Up;
            @AbilityLeft.started -= instance.OnAbilityLeft;
            @AbilityLeft.performed -= instance.OnAbilityLeft;
            @AbilityLeft.canceled -= instance.OnAbilityLeft;
            @AbilityRight_DownPress.started -= instance.OnAbilityRight_DownPress;
            @AbilityRight_DownPress.performed -= instance.OnAbilityRight_DownPress;
            @AbilityRight_DownPress.canceled -= instance.OnAbilityRight_DownPress;
            @AbilityRight_RelesePress.started -= instance.OnAbilityRight_RelesePress;
            @AbilityRight_RelesePress.performed -= instance.OnAbilityRight_RelesePress;
            @AbilityRight_RelesePress.canceled -= instance.OnAbilityRight_RelesePress;
            @Respawn.started -= instance.OnRespawn;
            @Respawn.performed -= instance.OnRespawn;
            @Respawn.canceled -= instance.OnRespawn;
            @Quit.started -= instance.OnQuit;
            @Quit.performed -= instance.OnQuit;
            @Quit.canceled -= instance.OnQuit;
            @Menu_Back.started -= instance.OnMenu_Back;
            @Menu_Back.performed -= instance.OnMenu_Back;
            @Menu_Back.canceled -= instance.OnMenu_Back;
            @DialogueSkip_Pressed.started -= instance.OnDialogueSkip_Pressed;
            @DialogueSkip_Pressed.performed -= instance.OnDialogueSkip_Pressed;
            @DialogueSkip_Pressed.canceled -= instance.OnDialogueSkip_Pressed;
            @DialogueNext_Pressed.started -= instance.OnDialogueNext_Pressed;
            @DialogueNext_Pressed.performed -= instance.OnDialogueNext_Pressed;
            @DialogueNext_Pressed.canceled -= instance.OnDialogueNext_Pressed;
            @InteractButton_Pressed.started -= instance.OnInteractButton_Pressed;
            @InteractButton_Pressed.performed -= instance.OnInteractButton_Pressed;
            @InteractButton_Pressed.canceled -= instance.OnInteractButton_Pressed;
            @MenuNavigation_Up.started -= instance.OnMenuNavigation_Up;
            @MenuNavigation_Up.performed -= instance.OnMenuNavigation_Up;
            @MenuNavigation_Up.canceled -= instance.OnMenuNavigation_Up;
            @MenuNavigation_Down.started -= instance.OnMenuNavigation_Down;
            @MenuNavigation_Down.performed -= instance.OnMenuNavigation_Down;
            @MenuNavigation_Down.canceled -= instance.OnMenuNavigation_Down;
            @MenuNavigation_Left.started -= instance.OnMenuNavigation_Left;
            @MenuNavigation_Left.performed -= instance.OnMenuNavigation_Left;
            @MenuNavigation_Left.canceled -= instance.OnMenuNavigation_Left;
            @MenuNavigation_Right.started -= instance.OnMenuNavigation_Right;
            @MenuNavigation_Right.performed -= instance.OnMenuNavigation_Right;
            @MenuNavigation_Right.canceled -= instance.OnMenuNavigation_Right;
            @OptionsMenuShift_Left.started -= instance.OnOptionsMenuShift_Left;
            @OptionsMenuShift_Left.performed -= instance.OnOptionsMenuShift_Left;
            @OptionsMenuShift_Left.canceled -= instance.OnOptionsMenuShift_Left;
            @OptionsMenuShift_Right.started -= instance.OnOptionsMenuShift_Right;
            @OptionsMenuShift_Right.performed -= instance.OnOptionsMenuShift_Right;
            @OptionsMenuShift_Right.canceled -= instance.OnOptionsMenuShift_Right;
        }

        public void RemoveCallbacks(IPlayerMovementActions instance)
        {
            if (m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerMovementActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerMovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerMovementActions @PlayerMovement => new PlayerMovementActions(this);
    public interface IPlayerMovementActions
    {
        void OnForward_Down(InputAction.CallbackContext context);
        void OnForward_Up(InputAction.CallbackContext context);
        void OnBackward_Down(InputAction.CallbackContext context);
        void OnBackward_Up(InputAction.CallbackContext context);
        void OnLeft_Down(InputAction.CallbackContext context);
        void OnLeft_Up(InputAction.CallbackContext context);
        void OnRight_Down(InputAction.CallbackContext context);
        void OnRight_Up(InputAction.CallbackContext context);
        void OnCameraRotateX(InputAction.CallbackContext context);
        void OnCameraRotateY(InputAction.CallbackContext context);
        void OnAbilityUp_Down(InputAction.CallbackContext context);
        void OnAbilityUp_Up(InputAction.CallbackContext context);
        void OnAbilityDown_Down(InputAction.CallbackContext context);
        void OnAbilityDown_Up(InputAction.CallbackContext context);
        void OnAbilityLeft(InputAction.CallbackContext context);
        void OnAbilityRight_DownPress(InputAction.CallbackContext context);
        void OnAbilityRight_RelesePress(InputAction.CallbackContext context);
        void OnRespawn(InputAction.CallbackContext context);
        void OnQuit(InputAction.CallbackContext context);
        void OnMenu_Back(InputAction.CallbackContext context);
        void OnDialogueSkip_Pressed(InputAction.CallbackContext context);
        void OnDialogueNext_Pressed(InputAction.CallbackContext context);
        void OnInteractButton_Pressed(InputAction.CallbackContext context);
        void OnMenuNavigation_Up(InputAction.CallbackContext context);
        void OnMenuNavigation_Down(InputAction.CallbackContext context);
        void OnMenuNavigation_Left(InputAction.CallbackContext context);
        void OnMenuNavigation_Right(InputAction.CallbackContext context);
        void OnOptionsMenuShift_Left(InputAction.CallbackContext context);
        void OnOptionsMenuShift_Right(InputAction.CallbackContext context);
    }
}
